#!/bin/sh
#/etc/init.d/myService
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec sudo forever --sourceDir=/home/pi/Kinetikami-Lamp/node-device/ -p /home/pi/Kinetikami-Lamp/node-device/ light.js
;;
stop)
exec sudo forever stop --sourceDir=/home/pi/Kinetikami-Lamp/node-device/ light.js
;;
*)
echo "Usage: /etc/init.d/myService {start|stop}"
exit 1
;;
esac
exit 0


